apiVersion: v1
kind: Service
metadata:
  name: keystone
  labels:
    name: keystone
spec:
  type: ClusterIP
  ports:
  - name: public
    port: 5000
  - name: admin
    port: 35357
  selector:
    name: keystone
